[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/agenda/2025-04-01-heros-zapatistes/index.html"
to = "/agenda/2025/heros-zapatistes/"

[[redirects]]
from = "/auberge-espagnole-a-la-casa-noesya/index.html"
to = "/codex-domus/auberge-espagnole-a-la-casa-noesya/"

[[redirects]]
from = "/organisations/index.html"
to = "/parties-prenantes/"

[[redirects]]
from = "/agenda/2026/cafe-papotage-enercoop/index.html"
to = "/agenda/2026/apero-papotage-enercoop/"

[[redirects]]
from = "/actualites/2024-05-19-decouverte-de-lannonce/index.html"
to = "/actualites/2024-05-01-decouverte-de-lannonce/"

[[redirects]]
from = "/agenda/2025-03-06-dia-de-muertos/index.html"
to = "/agenda/2025/dia-de-muertos/"

[[redirects]]
from = "/agenda/2025-03-06-lancement-maison-du-numerique/index.html"
to = "/agenda/2025/dia-de-muertos/"

[[redirects]]
from = "/Programme/index.html"
to = "/agenda/2025/fete-de-la-musique-2025/"

